# -*- makefile -*-

include config.mak
include Make.vars

pintossrc=$(abspath $(SRCDIR)/test/pintos)
pintosbuild=$(abspath $(build)/test/pintos)
#testsrc=$(abspath $(pintossrc)/$(ASSIGNMENT)/$(TEST))
testsrc=$(abspath $(pintossrc)/$(TEST))
#testbuild=$(abspath $(pintosbuild)/$(ASSIGNMENT))
testbuild=$(abspath $(pintosbuild))

#VPATH=$(abspath $(pintossrc)/$(ASSIGNMENT)) $(pintossrc)
VPATH=$(abspath $(pintossrc)) $(pintossrc)

TESTDIR = $(pintossrc)

MONITOR_SUBDIRS = sys threads mem devices hw peep lib devices/usb
VARIANTS = $(TEST_VARIANTS_ALL)
MDSKS =
MONITOR_DISKS =
PINTOS_DISKS =

BUILD_DIRS=
$(foreach variant,$(VARIANTS),$(eval	\
	$(variant)_BUILD_DIR=../$(NAME)-build.$(variant)))
$(foreach variant,$(VARIANTS),$(eval BUILD_DIRS+=$($(variant)_BUILD_DIR)))

$(BUILD_DIRS):
	mkdir -p $@

all: kernel.bin loader.bin
include $(TESTDIR)/Make.config
include $(testsrc)/Make.vars
include $(TESTDIR)/tests/Make.tests

$(foreach test, $(TESTS), $(foreach variant, $(VARIANTS),									\
	$(eval MDSKS += $(test).$(variant).mdsk)))
$(foreach test, $(TESTS), $(foreach variant, $(VARIANTS),									\
	$(eval MONITOR_DISKS+=$($(variant)_BUILD_DIR)/$(notdir $(test)).monitor.dsk)))
$(foreach test, $(TESTS), $(eval PINTOS_DISKS += $(test).dsk))
$(foreach test, $(TESTS), $(eval PINTOS_NOBIOS_DISKS += $(test).nobios.dsk))

$(foreach test, $(TESTS), $(foreach variant, $(VARIANTS),			\
	$(eval $(test).$(variant).mdsk: variant=$(variant))))
$(foreach test,$(TESTS),$(foreach variant,$(VARIANTS),\
	$(eval $(test).$(variant).mdsk: test=$(test))))

#$(foreach test, $(TESTS), $(foreach variant, $(VARIANTS),			\
#  $(eval $(test).$(variant).mdsk: $($(variant)_BUILD_DIR))))

$(foreach test, $(TESTS), $(foreach variant, $(VARIANTS),			\
	$(eval $(test).$(variant).mdsk: 														\
					$($(variant)_BUILD_DIR)/$(notdir $(test)).monitor.dsk)))
$(foreach test, $(TESTS), $(foreach variant, $(VARIANTS), 		\
	$(eval $(test).$(variant).mdsk:	$(test).nobios.dsk)))

$(foreach test, $(TESTS), $(foreach variant, $(VARIANTS), \
	$(eval $($(variant)_BUILD_DIR)/$(notdir $(test)).monitor.dsk: \
					$($(variant)_BUILD_DIR)/config.h \
					$($(variant)_BUILD_DIR)/config.mak)))
$(foreach test, $(TESTS), $(foreach variant, $(VARIANTS), 		\
	$(eval $($(variant)_BUILD_DIR)/$(notdir $(test)).monitor.dsk:	$(test).nobios.dsk)))
$(foreach test, $(TESTS), $(foreach variant, $(VARIANTS), \
	$(eval $($(variant)_BUILD_DIR)/$(notdir $(test)).monitor.dsk: \
					$($(variant)_BUILD_DIR)/Makefile)))
$(foreach variant, $(VARIANTS), $(eval $($(variant)_BUILD_DIR)/config.h \
	$($(variant)_BUILD_DIR)/config.mak: $(SRCDIR)/configure))

#.INTERMEDIATE: $(MDSKS) $(MONITOR_DISKS) $(PINTOS_DISKS)

$(MDSKS):
	cat $(test).nobios.dsk $($(variant)_BUILD_DIR)/$(notdir $(test)).monitor.dsk > $@
	#rm -f $(test).dsk.split.*
	perl $(SRCDIR)/misc/add_monitor.pl $@ 	\
		$($(variant)_BUILD_DIR)/$(notdir $(test)).monitor.dsk \
		$(MONITOR_OFFSET) $(test).nobios.dsk

%config.h %config.mak:
	bash -c \
	"cd $($(variant)_BUILD_DIR) && source_path=$(SRCDIR) ndebug=1 \
				$(TEST_CONFIGURE_FLAGS) $(SRCDIR)/configure"

%monitor.dsk:
	make -C $($(variant)_BUILD_DIR) $@ 							\
		MONITOR_OFFSET=$(MONITOR_OFFSET) 							\
		RR_FLAGS="$(RR_FLAGS)"

%Makefile: $(SRCDIR)/Makefile.build
	cp $< $@

# Compiler and assembler options.
#kernel.bin: CPPFLAGS += -I$(TESTDIR)/$(ASSIGNMENT)/lib/kernel
kernel.bin: CPPFLAGS += -I$(TESTDIR)/lib/kernel

# Core kernel.
threads_SRC  = threads/start.S		# Startup code.
threads_SRC += threads/init.c		# Main program.
threads_SRC += threads/thread.c		# Thread management core.
threads_SRC += threads/switch.S		# Thread switch routine.
threads_SRC += threads/interrupt.c	# Interrupt core.
threads_SRC += threads/intr-stubs.S	# Interrupt stubs.
threads_SRC += threads/synch.c		# Synchronization.
threads_SRC += threads/palloc.c		# Page allocator.
threads_SRC += threads/malloc.c		# Subpage allocator.

# Device driver code.
devices_SRC  = devices/pit.c		# Programmable interrupt timer chip.
devices_SRC += devices/timer.c		# Periodic timer device.
devices_SRC += devices/kbd.c		# Keyboard device.
devices_SRC += devices/vga.c		# Video device.
devices_SRC += devices/serial.c		# Serial port device.
devices_SRC += devices/block.c		# Block device abstraction layer.
devices_SRC += devices/partition.c	# Partition block device.
devices_SRC += devices/ide.c		# IDE disk block device.
devices_SRC += devices/input.c		# Serial and keyboard input.
devices_SRC += devices/intq.c		# Interrupt queue.
devices_SRC += devices/rtc.c		# Real-time clock.
devices_SRC += devices/shutdown.c	# Reboot and power off.
devices_SRC += devices/speaker.c	# PC speaker.
devices_SRC += devices/usb/ehci.c
devices_SRC += devices/usb/uhci.c
devices_SRC += devices/usb/usbdevice.c
devices_SRC += devices/usb/usbhub.c
devices_SRC += devices/usb/usbmsd.c
devices_SRC += devices/pci.c

# Library code shared between kernel and user programs.
lib_SRC  = lib/debug.c			# Debug helpers.
lib_SRC += lib/random.c			# Pseudo-random numbers.
lib_SRC += lib/stdio.c			# I/O library.
lib_SRC += lib/stdlib.c			# Utility functions.
lib_SRC += lib/string.c			# String functions.
lib_SRC += lib/arithmetic.c		# 64-bit arithmetic for GCC.
lib_SRC += lib/ustar.c			# Unix standard tar format utilities.

# Kernel-specific library code.
lib/kernel_SRC  = lib/kernel/debug.c	# Debug helpers.
lib/kernel_SRC += lib/kernel/list.c	# Doubly-linked lists.
lib/kernel_SRC += lib/kernel/bitmap.c	# Bitmaps.
lib/kernel_SRC += lib/kernel/hash.c	# Hash tables.
lib/kernel_SRC += lib/kernel/console.c	# printf(), putchar().

# User process code.
userprog_SRC  = userprog/process.c	# Process loading.
userprog_SRC += userprog/pagedir.c	# Page directories.
userprog_SRC += userprog/exception.c	# User exception handler.
userprog_SRC += userprog/syscall.c	# System call handler.
userprog_SRC += userprog/gdt.c		# GDT initialization.
userprog_SRC += userprog/tss.c		# TSS management.

# No virtual memory code yet.
vm_SRC = vm/page.c
vm_SRC += vm/frame.c
vm_SRC += vm/swap.c

# Filesystem code.
filesys_SRC  = filesys/filesys.c	# Filesystem core.
filesys_SRC += filesys/free-map.c	# Free sector bitmap.
filesys_SRC += filesys/file.c		# Files.
filesys_SRC += filesys/directory.c	# Directories.
filesys_SRC += filesys/inode.c		# File headers.
filesys_SRC += filesys/fsutil.c		# Utilities.
filesys_SRC += filesys/cache.c		# Cache.

SOURCES = $(foreach dir,$(KERNEL_SUBDIRS),$($(dir)_SRC))
OBJECTS = $(patsubst %.c,%.o,$(patsubst %.S,%.o,$(SOURCES)))
DEPENDS = $(patsubst %.o,%.d,$(OBJECTS))

threads/kernel.lds.s: CPPFLAGS += -P
threads/kernel.lds.s: threads/kernel.lds.S threads/loader.h

kernel.o: threads/kernel.lds.s $(OBJECTS) 
	$(LD) -T $< -o $@ $(OBJECTS)

kernel.bin: kernel.o
	$(OBJCOPY) -R .note -R .comment -S $< $@

threads/loader.o: threads/loader.S
	$(CC) -c $< -o $@ $(ASFLAGS) $(CPPFLAGS) $(DEFINES)

threads/loader.nobios.o: threads/loader.S
	$(CC) -c $< -o $@ $(ASFLAGS) $(CPPFLAGS) $(DEFINES) -DNOBIOS

loader.bin loader.nobios.bin: %.bin: threads/%.o
	$(LD) -N -e 0 -Ttext 0x7c00 --oformat binary -o $@ $<

os.dsk: kernel.bin
	cat $^ > $@

clean::
	rm -f $(OBJECTS) $(DEPENDS) 
	rm -f threads/loader.o threads/kernel.lds.s threads/loader.d
	rm -f kernel.bin.tmp
	rm -f kernel.o kernel.lds.s
	rm -f kernel.bin loader.bin
	rm -f bochsout.txt bochsrc.txt
	rm -f results grade

#Makefile: $(SRCDIR)/Makefile.build
#	cp $< $@

-include $(DEPENDS)
