#!/usr/bin/expect -f

set timeout -1
stty
set disk_image [lindex $argv 0]
set disk_name  [lindex $argv 1]
#set host 10.20.3.27
set USER $env(USER)
set PASSWORD $env(PASSWORD)
set WEBSERVER systems.cse.iitd.ernet.in

spawn scp $disk_image $USER@$WEBSERVER:./$disk_name
expect "*password*"
send "$PASSWORD\r"
sleep 1
expect "$USER@*"

spawn ssh $USER@$WEBSERVER qsub -b y ./$disk_name
expect "*password*"
send "$PASSWORD\r"
expect eof

exit 0
